import { Inter } from "next/font/google";
import "@/ui/global.css";
import React from "react";
import  SessionProvider  from "./lib/components/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "vee1",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="overflow-hidden">
				<SessionProvider>{children}</SessionProvider>
			</body>
		</html>
	);
}
