import { Inter } from "next/font/google";
import "@/ui/global.css";
import React from "react";
import  {Provider}  from "@/app/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "vee1",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="overflow-hidden">
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
